// APPLICATION
export const APP_LOADING = 'APP_LOADING';

// ASYNC
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';

// HOME
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';

// LOGIN
export const LOGIN_PAGE_LOADED = 'LOGIN_PAGE_LOADED';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCEDED = 'LOGIN_SUCCEDED';

// SINGUP
export const SIGNUP_PAGE_LOADED = 'SIGNUP_PAGE_LOADED';
export const SIGNUP_PAGE_UNLOADED = 'SIGNUP_PAGE_UNLOADED';
export const SIGNUP_REQUESTED = 'SIGNUP_REQUESTED';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNUP_SUCCEDED = 'SIGNUP_SUCCEDED';

// LOGOUT
export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';
export const VALIDATE_FIELDS = 'VALIDATE_FIELDS';

// FORMS
export const UPDATE_FIELD_LOGIN = 'UPDATE_FIELD_LOGIN';
export const VALIDATE_FIELDS_LOGIN = 'VALIDATE_FIELDS_LOGIN';
export const UPDATE_FIELD_SIGNUP = 'UPDATE_FIELD_SIGNUP';
export const VALIDATE_FIELDS_SIGNUP = 'VALIDATE_FIELDS_SIGNUP';

// SYNTHESIS 
export const SYNTHESIS_PAGE_LOADED = 'SYNTHESIS_PAGE_LOADED';
export const SYNTHESIS_PAGE_UNLOADED = 'SYNTHESIS_PAGE_UNLOADED';
export const SYNTHESIS_REQUESTED = 'SYNTHESIS_REQUESTED';
export const UPDATE_FIELD_SYNTHESIS = 'UPDATE_FIELD_SYNTHESIS';

// SYNTHESIS DOC 
export const SYNTHESISDOC_PAGE_LOADED = 'SYNTHESISDOC_PAGE_LOADED';
export const SYNTHESISDOC_PAGE_UNLOADED = 'SYNTHESISDOC_PAGE_UNLOADED';
