//APPLICATION
export const APP_LOADING = 'APP_LOADING';
export const APP_LOADING_SUCCESS = 'APP_LOADING_SUCCESS';
export const APP_LOADING_ERROR = 'APP_LOADING_ERROR';

//ASYNC 
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';

// HOME 
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';

// LOGIN
export const LOGIN_PAGE_LOADED = 'LOGIN_PAGE_LOADED';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED'; 
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCEDED = 'LOGIN_SUCCEDED';

// SINGUP
export const SIGNUP_PAGE_LOAD = 'SIGNUP_PAGE_LOAD';
export const SIGNUP_PAGE_UNLOADED = 'SIGNUP_PAGE_UNLOADED'; 
export const SIGNUP_REQUESTED = 'SIGNUP_REQUESTED';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNUP_SUCCEDED = 'SIGNUP_SUCCEDED';

// FORMS 
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';

